export const units = [
  {id: 1, name: 'Bags', value: 'bags'},
  {id: 2, name: 'Nos', value: 'nos'},
  {id: 3, name: 'Box', value: 'box'},
  {id: 4, name: 'ct', value: 'ct'},
  {id: 5, name: 'Each', value: 'each'},
  {id: 6, name: 'pk', value: 'pk'},
  {id: 7, name: 'Doz', value: 'doz'},
  {id: 8, name: 'm', value: 'm'},
  {id: 9, name: 'mm', value: 'mm'},
  {id: 10, name: 'cm', value: 'cm'},
  {id: 11, name: 'ft', value: 'ft'},
  {id: 12, name: 'rft', value: 'rft'},
  {id: 13, name: 'in', value: 'in'},
  {id: 14, name: 'yd', value: 'yd'},
  {id: 15, name: 'Km', value: 'km'},
  {id: 16, name: 'sqm', value: 'sqm'},
  {id: 17, name: 'sqmm', value: 'sqmm'},
  {id: 18, name: 'sqcm', value: 'sqcm'},
  {id: 19, name: 'sqft', value: 'sqft'},
  {id: 20, name: 'sqin', value: 'sqin'},
  {id: 21, name: 'sqyd', value: 'sqyd'},
  {id: 22, name: 'cum', value: 'cum'},
  {id: 23, name: 'T', value: 't'},
  {id: 24, name: 'Kg', value: 'kg'},
  {id: 25, name: 'g', value: 'g'},
  {id: 26, name: 'Mg', value: 'mg'},
  {id: 27, name: 'Lb', value: 'lb'},
  {id: 28, name: 'oz', value: 'oz'},
  {id: 29, name: 'MT', value: 'MT'},
  {id: 30, name: 'Ltr', value: 'Ltr'},
  {id: 31, name: 'Pcs', value: 'Pcs'},
  {id: 32, name: '%', value: '%'},
];

export const months = {
  0: 'Jan',
  1: 'Feb',
  2: 'Mar',
  3: 'Apr',
  4: 'May',
  5: 'Jun',
  6: 'Jul',
  7: 'Aug',
  8: 'Sep',
  9: 'Oct',
  10: 'Nov',
  11: 'Dec',
};
